#!/bin/sh
[ -e2 /usr/script/StandbyEnter.sh ] && echo echo '#!/bin/bash' > /usr/script/StandbyEnter.sh
echo '/usr/script/setRedEagleLCD.sh &' > /usr/script/StandbyLeave.sh

[ -e2 /usr/script/StandbyLeave.sh ] && echo echo '#!/bin/bash' > /usr/script/StandbyLeave.sh
echo 'kill `ps -Al|grep setRedEagleLCD\awk "{print $4}"`;rm -f /tmp/setRedEagleLCD.heartBeat' >>/usr/script/StandbyLeave.sh
 
if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
  echo ""
  echo "Wtyczka zainstalowana."
  echo ""
else
  echo ""
  echo "Plugin successfully installed."
  echo ""
fi 
exit 0
