#!/bin/sh

find /usr/share/enigma2/vfd_skin -iname skin_vfd_U4K_HMR_*.xml|while read f; do
  #echo "$f"
  sed -i 's/jOOzekPiconAnimation/j00zekPiconAnimation/g' $f
  sed -i 's/jOOzekPicons/j00zekPicons/g' $f
  sed -i 's/jOOzekPixmap/j00zekPixmap/g' $f
  sed -i 's/jOOzekRefreshBingPicOfTheDay/j00zekRefreshBingPicOfTheDay/g' $f
  sed -i 's;vfd_skin/Homar/BingPicOfTheDay.jpg;BlackHarmony/icons/BingPicOfTheDay.jpg;g' $f
  sed -i 's/jOOzekSun/j00zekSun/g' $f
  sed -i 's;convert type="ServiceName2";convert type="BlackHarmonyServiceName2";g' $f
  #sed -i 's;;;g' $f
done

exit 0
