#!/bin/sh
if [ `ps -ef|grep -v grep|grep opkg|grep -c remove` -ge 1 ];then
  #czyszczenie ewentualnych pozostalosci, ale tylko, jak ktos wywala calkowicie skorke
  rm -rf /usr/share/enigma2/BlackHarmony/allPreviews/* 2 > /dev/null
fi
exit 0
