#!/bin/sh
instDir='/usr/share/enigma2/HomarLCDskins'
skinsDir='/usr/share/enigma2'

if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
 lang='PL'
else
 lang='EN'
fi

#check tuner model
if [ -e /proc/stb/info/vumodel ];then
  model=`cat /proc/stb/info/vumodel`
fi

#check image type
if [ -e $skinsDir/vfd_skin ];then
  systemType='VTI'
  find $instDir/model.$model -iname skin_LCD_*.xml|while read f; do
    nf=`basename $f|sed 's/skin_LCD_/skin_vfd_/g'`
    ln -sf "$f" "$skinsDir/$nf"
  done
elif [ -d $skinsDir/display ];then
  systemType='openATV'
  find $instDir/model.$model -iname skin_LCD_*.xml|while read f; do
    nf=`basename $f .xml|sed 's/skin_LCD_//g'`
    mkdir -p "$skinsDir/display/$nf"
    ln -sf "$f" "$skinsDir/display/$nf/skin_display.xml"
  done
elif [ "`cat /etc/opkg/all-feed.conf 2> /dev/null|grep -c 'openpli-7'`" -gt 0 ];then
  systemType='openPLI-7'
else
  systemType='UNKNOWN'
fi
#info
echo "$systemType" > /usr/share/enigma2/BlackHarmony/image.info
if [ $lang == 'PL' ]; then
  echo
  echo "Konfiguracja dla $systemType $model"
else
  echo
  echo "Configuring for $systemType $model"
fi

exit 0
