#!/bin/sh
exit 0

#check tuner model
if [ -e /proc/stb/info/vumodel ];then
  model=`cat /proc/stb/info/vumodel`
fi

if [ `echo 'duo4k,solo4k,ultimo4k,uno4k'|grep -c "$model"` -lt 1 ];then
  echo "tuner not compatible"
  exit 1
fi
