#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/BoardsReader 2 > /dev/null
if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
  echo ""
  echo "Wtyczka skasowana. Przeładuj teraz GUI!"
  echo ""
else
  echo ""
  echo "Plugin removed. You should restart GUI!"
  echo ""
fi 
exit 0
