#!/bin/sh
if [ -e /usr/share/enigma2/BLACK_FHD_VTI/skin_user_bar ];then
  cp -f /usr/share/enigma2/BLACK_FHD_VTI/skin_user_bar/* /usr/share/enigma2/BLACK_FHD_VTI/menu/ 2>/dev/null
fi

#final message
if [ -e /usr/share/enigma2/BLACK_FHD_VTI/UserSkin_Selections/ ];then
  if `ls /usr/share/enigma2/BLACK_FHD_VTI/UserSkin_Selections/ |grep -q '.xml'`;then
    if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
      echo
      echo "Nie zapomnij wejść do wtyczki UserSkin i zaktualizować ustawienia"
    else
      echo
      echo "Do not forget to enter UserSkin plugin and do actualization of settings"
    fi
    cd /usr/share/enigma2/BLACK_FHD_VTI/UserSkin_Selections
    find -L . -name . -o -type d -prune -o -type l -exec rm {} +
    cd ~
  fi
fi
sleep 5
exit 0