#!/bin/sh
if `ps -ef|grep -v grep|grep opkg|grep remove`;then
  #czyszczenie ewentualnych pozostalosci, ale tylko, jak ktos wywala calkowicie skorke
  rm -rf /usr/share/enigma2/BLACK_FHD_VTI 2 > /dev/null
  if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
    echo ""
    echo "skórka skasowana. Przeładuj teraz GUI!"
    echo ""
  else
    echo ""
    echo "Skin removed. You should restart GUI!"
    echo ""
  fi
fi
exit 0
