#!/bin/sh
if [ `grep -c ARMv7 < /proc/cpuinfo` -lt 1 ];then
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/AlternativeSoftCamManager/CAMbin/oscam-svn*arm* 2 > /dev/null
fi 
if [ `grep -c mips < /proc/cpuinfo` -lt 1 ];then
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/AlternativeSoftCamManager/CAMbin/oscam-svn*mips* 2 > /dev/null
fi 
if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
  echo ""
  echo "Wtyczka zainstalowana. Przeładuj teraz GUI!"
  echo ""
else
  echo ""
  echo "Plugin successfully installed. You should restart GUI!"
  echo ""
fi 
exit 0
