#!/bin/sh
if [ -e /usr/share/enigma2/BlackHarmony/skin_user_bar ];then
  cp -f /usr/share/enigma2/BlackHarmony/skin_user_bar/* /usr/share/enigma2/BlackHarmony/menu/ 2>/dev/null
fi

if [ ! -e /usr/lib/enigma2/python/Plugins/Extensions/MSNweather ]; then
  if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
    echo
    echo "UWAGA:"
    echo "Aby działało w skórce wyświetlanie pogody, musisz doinstalować wtyczkę z pogodą MSN"
  else
    echo
    echo "ATTENTION:"
    echo "You need to install eMSN weather plugin plugin to use weather components in skin"
  fi
fi

if [ -e /usr/lib/enigma2/python/skin.py ];then #patching BlackHole skin.py to be less resstrictive, similar rules to openATV
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*pixmap file %s not found!.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*need color and name, got %s %s.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*component with name .* was not found in skin of screen.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*specified related screen .* was not found in screen.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*source .* was not found in screen.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*you must define a renderer with render= for source.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  sed -i 's/\(^[ \t]*\)raise SkinError\(.*applet type .* unknown!.*\)/\1print\2/' /usr/lib/enigma2/python/skin.py
  echo
  echo '/usr/lib/enigma2/python/skin.py patched'
fi

#build skin.xml
echo '<skin>' > /usr/share/enigma2/BlackHarmony/skin.xml
cat /usr/share/enigma2/BlackHarmony/skin-header.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
cat /usr/share/enigma2/BlackHarmony/screens-common.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
if [ -e /usr/lib/enigma2/python/Plugins/SystemPlugins/VTIPanel ];then
  cat /usr/share/enigma2/BlackHarmony/screens-VTI_specific.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
  echo 'VTI image'
elif [ -e /usr/lib/enigma2/python/Plugins/Extensions/Infopanel ];then
  cat /usr/share/enigma2/BlackHarmony/screens-openATV_specific.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
  echo 'openATV image'
elif [ -e /usr/lib/enigma2/python/Blackhole ];then
  cat /usr/share/enigma2/BlackHarmony/screens-BlackHole_specific.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
  sed -i 's/if compat == "passed"/if compat == compat/g' /usr/lib/enigma2/python/Plugins/SystemPlugins/SkinSelector/plugin.py
  echo 'VTI BlackHole image'
elif [ -e //etc/init.d/start_pkt.sh ];then
  cat /usr/share/enigma2/BlackHarmony/screens-PKT_specific.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
  echo 'PKT image'
else
  cat /usr/share/enigma2/BlackHarmony/screens-unknown.xml >> /usr/share/enigma2/BlackHarmony/skin.xml
  echo 'UNKNOWN image'
fi
echo '</skin>' >> /usr/share/enigma2/BlackHarmony/skin.xml
sync
#prepare some links
find /usr/share/enigma2/BlackHarmony/allScreens -iname skin_channelselection_*.xml|while read f; do
  #echo "$f"
  if [ `echo "$f"|grep -c '/ChannelSelections/'` -eq 0 ]; then
    f2="`echo \"$f\"|sed 's;\(^.*/allScreens/\).*\(/skin_*\);\1ChannelSelections\2;'`"
    #echo "$f2"
    ln -sf "$f" "$f2"
  fi
done
find /usr/share/enigma2/BlackHarmony/allScreens -iname skin_infobar_*.xml|while read f; do
  #echo "$f"
  if [ `echo "$f"|grep -c '/Infobars/'` -eq 0 ]; then
    f2="`echo \"$f\"|sed 's;\(^.*/allScreens/\).*\(/skin_*\);\1Infobars\2;'`"
    #echo "$f2"
    ln -sf "$f" "$f2"
  fi
done
find /usr/share/enigma2/BlackHarmony/allScreens -iname skin_secondinfobar_*.xml|while read f; do
  #echo "$f"
  if [ `echo "$f"|grep -c '/Secondinfobars/'` -eq 0 ]; then
    f2="`echo \"$f\"|sed 's;\(^.*/allScreens/\).*\(/skin_*\);\1Secondinfobars\2;'`"
    #echo "$f2"
    ln -sf "$f" "$f2"
  fi
done
sync
find /usr/share/enigma2/BlackHarmony/allScreens -iname skin_volume_*.xml|while read f; do
  #echo "$f"
  if [ `echo "$f"|grep -c '/Volume/'` -eq 0 ]; then
    f2="`echo \"$f\"|sed 's;\(^.*/allScreens/\).*\(/skin_*\);\1Volume\2;'`"
    #echo "$f2"
    ln -sf "$f" "$f2"
  fi
done
sync
#bing image if not exists
[ -e /usr/share/enigma2/BlackHarmony/icons/BingPicOfTheDay.jpg ] || /usr/lib/enigma2/python/Components/j00zekBING.py
#deleting skin_user when his components modified
UserSkinDate=`date -r /usr/share/enigma2/BlackHarmony/mySkin/skin_user_BlackHarmony.xml +"%s"`
find /usr/share/enigma2/BlackHarmony/UserSkin_Selections/ -iname skin_*.xml|while read f; do
  widgetDate=`date -r $f +"%s"`
  if [[ $UserSkinDate -lt $widgetDate ]]; then
    [ -e /usr/share/enigma2/BlackHarmony/mySkin/skin_user_BlackHarmony.xml ] && rm -f /usr/share/enigma2/BlackHarmony/mySkin/skin_user_BlackHarmony.xml
    [ -e /etc/enigma2/skin_user_BlackHarmony.xml ] && rm -f /etc/enigma2/skin_user_BlackHarmony.xml
    break
  fi
done
#set GS marker
if `grep -q 'config.plugins.UserSkin.SafeMode=true' </etc/enigma2/settings`; then
  touch /etc/enigma2/skinModified
fi
#final message
if [ -e /usr/share/enigma2/BlackHarmony/UserSkin_Selections/ ];then
  if [ -e /usr/share/enigma2/BlackHarmony/mySkin/skin_user_BlackHarmony.xml ];then
    if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
      echo
      echo "Skórka została zaktualizowana"
    else
      echo
      echo "Skin has been updated"
    fi
  else
    if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
      echo
      echo "Nie zapomnij wejść do wtyczki UserSkin i wygenerować ponownie skórkę użytkownika"
    else
      echo
      echo "Do not forget to enter UserSkin plugin and recreate user skin"
    fi
  fi
fi
sleep 5
exit 0